### ISSUE TITLE
对于某些模块兼容define.cmd方式,transport会丢失内容

### ISSUE THREAD

**Issue by guilipan** [guilipan/gulp-seajs-transport#2]
现有的方式不支持如下的写法,因为会仅仅替换define函数部分并重新生成新的文件,从而丢失定义Animal对象的内容

```
(function () {

    function Animal(a, b) {
             this.a = a;
             this.b = b;
    }

    if (typeof define === "function" && define.cmd) {
     // 有 Sea.js 等 CMD 模块加载器存在
         define(function (require, exports, module) {
                 module.exports = Animal;
         })
    }

})()
```

会变成

```
define("animal",[],function (require, exports, module) {
                 module.exports = Animal;
})
```

**Comment by piaer** [comment]
请问使用过gulp吗

**Comment by guilipan** [comment]
@piaer 什么意思？这个就是gulp的插件

**Comment by piaer** [comment]
我最近就是在搞这个文件依赖的东西，但是这个gulp-seajs-transport用了老是报
TypeError: Cannot read property 'dependencies' of undefined
这个错误，都不知道怎么弄了，能请教一下吗。

**Comment by guilipan** [comment]
@piaer 升级插件到最新的0.0.10版本,然后需要被处理的js文件必须是符合cmd规范的,然后你再试下

**Comment by piaer** [comment]
@guilipan 请问有例子吗

**Comment by guilipan** [comment]
这个项目首页有相关例子
```
var transport = require("gulp-seajs-transport");
var gulp = require("gulp");

gulp.task("default",function(){
  gulp.src("./testfiles/**/*.js")
        .pipe(transport())
        .pipe(gulp.dest("./dist"));
}) 

```

**Comment by piaer** [comment]
@guilipan 

你好，然后我老是发生这种错误，是怎么回事呢



                var newAstSeaModule = {id: newId, dependencies: oldAstSeaModule.
dependencies                                                                               ^

TypeError: Cannot read property 'dependencies' of undefined

**Comment by guilipan** [comment]
你用的版本不是最新的吧，请升级到最新的0.0.10版本

**Comment by piaer** [comment]
define("index/js/init-sites-17zwdN-index", ["demo/widgets/17zwdN/rebirth-very-top/js/init-rebirth-very-top", "demo/widgets/17zwdN/rebirth-elevator/js/init-rebirth-elevator", "demo/widgets/17zwdN/rebrith-drift-adshow/js/init-rebrith-drift-adshow", "demo/widgets/17zwdN/rebirth-header/js/init-rebirth-header", "demo/widgets/17zwdN/rebirth-min-nav/js/init-rebirth-min-nav", "demo/widgets/17zwdN/rebirth-hint/js/init-rebirth-hint", "demo/widgets/17zwdN/rebirth-function-gather/js/init-rebirth-function-gather", "demo/widgets/17zwdN/rebirth-s4/js/init-rebirth-s4", "demo/widgets/17zwdN/rebirth-hot/js/init-rebirth-hot", "demo/widgets/17zwdN/rebirth-rotate-floor/js/init-rebirth-rotate-floor", "demo/widgets/17zwdN/rebirth-hot-sell-recommend/js/init-rebirth-hot-sell-recommend"], function(require, exports, module) {

});
这个是gulp 编译

--------------------------------------------------------------------------------------


define("demo/sites-concated/17zwdN/index/js/init-sites-17zwdN-index", [ "demo/widgets/17zwdN/rebirth-very-top/js/init-rebirth-very-top", "jquery/jquery/1.10.1/jquery", "demo/javascript/piaer-j-lazyload", "demo/widgets/17zwdN/rebirth-elevator/js/init-rebirth-elevator", "arale/sticky/1.3.1/sticky", "$", "demo/widgets/17zwdN/rebrith-drift-adshow/js/init-rebrith-drift-adshow", "demo/javascript/x", "demo/widgets/17zwdN/rebirth-header/js/init-rebirth-header", "demo/widgets/17zwdN/rebirth-min-nav/js/init-rebirth-min-nav", "demo/widgets/17zwdN/rebirth-hint/js/init-rebirth-hint", "demo/widgets/17zwdN/rebirth-function-gather/js/init-rebirth-function-gather", "demo/widgets/17zwdN/rebirth-function-gather/js/jPages", "demo/widgets/17zwdN/rebirth-function-gather/js/searcher", "demo/widgets/17zwdN/rebirth-function-gather/js/init-market-nav", "gallery/underscore/1.4.4/underscore", "gallery/backbone/1.0.0/backbone", "gallery/handlebars/1.0.2/handlebars", "demo/widgets/17zwdN/rebirth-function-gather/js/ShopsView", "gallery/json/1.0.3/json", "gallery/store/1.3.7/store", "arale/overlay/1.1.3/mask", "arale/position/1.0.1/position", "arale/iframe-shim/1.0.2/iframe-shim", "arale/widget/1.1.1/widget", "arale/base/1.1.1/base", "arale/class/1.1.0/class", "arale/events/1.1.0/events", "demo/widgets/17zwdN/rebirth-function-gather/js/ShopCollection", "demo/widgets/17zwdN/rebirth-function-gather/js/ShopModel", "arale/switchable/1.0.0/tabs", "arale/easing/1.0.0/easing", "demo/widgets/17zwdN/rebirth-s4/js/init-rebirth-s4", "demo/widgets/17zwdN/rebirth-hot/js/init-rebirth-hot", "demo/widgets/17zwdN/rebirth-rotate-floor/js/init-rebirth-rotate-floor", "demo/widgets/17zwdN/rebirth-hot-sell-recommend/js/init-rebirth-hot-sell-recommend" ], function(require, exports, module) {
   
});

这个是grunt编译的，用的是 grunt-cmd-transport 插件
grunt这个可以带过去spm的 alias配置

请问一下   gulp-seajs-transport 有办法吗

**Comment by guilipan** [comment]
@piaer  gulp-seajs-transport并不要求模块有package.json的配置文件,如果你需要按照原来的方式的话，你可以看下官方的[gulp-spm模块](https://github.com/spmjs/gulp-spm)
