### ISSUE TITLE
模块ID重复增加项目根目录

### ISSUE THREAD

**Issue by shiminghua** [guilipan/gulp-seajs-transport#5]
问题：多文件抽取依赖，只有第一个文件的依赖是正确的。其他的都类似：  D:/gulp/src/js/home/b

原因：如下边 options.base 的输出，options.base 会一直增加 file.cwd 字符串。

D:\gulp\src\js\
D:\gulp\D:\gulp\src\js\
D:\gulp\D:\gulp\D:\gulp\src\js\
D:\gulp\D:\gulp\D:\gulp\D:\gulp\src\js\

**Comment by guilipan** [comment]
已修复，多谢反馈

**Comment by shiminghua** [comment]
在设置 base 参数的情况下所有依赖ID： D:/gulp/src/js/home/b

我的修改代码，基本满足了我的需求。

var BASE;

BASE = options.base;

if (BASE) {

                options.base = path.join(file.cwd, BASE);

            }

            else {

                options.base = file.base;

            }
