### ISSUE TITLE
求助：TypeError: Cannot read property 'dependencies' of undefined

### ISSUE THREAD

**Issue by zhaobao** [guilipan/gulp-seajs-transport#8]
求助，类型错误，未定义dependencies，这个问题是怎么产生的？
gulp.task('script', ['clean_js'], function() {
    gulp.src(SRC.js + '**/*.js')
        .pipe(transport())
        .pipe(uglify())
        .pipe(gulp.dest(DEST.js));
});

define(function(require, exports) {
    var value = require('helper/value');
    exports.init = function() {
        console.log(value.getMiliTime());
    }
});

**Comment by guilipan** [comment]
@zhaobao  代码贴出来看下，错误截下图

**Comment by zhaobao** [comment]
@guilipan 
这个是代码
![Uploading 2015-03-23_140128.png . . .]()
这个是错误提示
![Uploading 2015-03-23_140258.png . . .]()

**Comment by henryleu** [comment]
我也遇到同样的问题了，我退回到0.0.5去了

**Comment by guilipan** [comment]
@zhaobao 能看到gulp-seajs-transport下的node_modules目录里面cmd-utils的版本号是多少吗？

**Comment by zhaobao** [comment]
@guilipan 0.3.13

**Comment by guilipan** [comment]
@zhaobao 你去掉uglify插件试下单纯跑transport能不能顺利执行

**Comment by zhaobao** [comment]
@guilipan 还是一样的错误

**Comment by guilipan** [comment]
@zhaobao 请将你的文件打包发到我邮箱guilipan@163.com,我分析一下，目前我这里没法重现

**Comment by zhaobao** [comment]
@guilipan https://github.com/zhaobao/webdemo/tree/problem 我这个项目里有个problem的分支，非常感谢！

**Comment by guilipan** [comment]
@zhaobao  你的项目里面有非cmd格式的文件存在，如内容为空等,我已经在0.0.9版本添加了判断

**Comment by xyyjk** [comment]
![qq 20150405154043](https://cloud.githubusercontent.com/assets/2508421/6996196/0bcdb298-dbab-11e4-9ff0-e73076ab59ae.png)

有时为了方便transport后执行其他的任务流，例如uglify，gulp.src直接引入了js的根目录，其中有部分文件确实不是cmd格式的文件，这时运行任务时就会抛出异常并卡住，而使用0.0.6的版本如果不是cmd格式的文件会跳过不处理，保证任务流能进行下去。希望还能将此机制还原。 @guilipan

**Comment by guilipan** [comment]
@xyyjk  像你的场景最好是分成2种类型的文件执行不同的任务,现在0.0.10版本会抛出异常就是为了帮助早点发现这些问题,而且此插件仅仅是为了处理seajs的cmd文件而存在的,所以在插件内置可能会遇到其他问题,因为一般transport后还可能有concat的需求,可能会造成其他异常
